const Web3 = require('web3');
var web3 = new Web3('ws://52.147.196.54:8545/');
const { BN } = require("@openzeppelin/test-helpers");
const eighteenDecimals = new BN(10).pow(new BN(18));
const getAccounts = async () => {
    await web3.eth.getAccounts(console.log);
}

const getBalance = async (account) => {
    const balance = await web3.eth.getBalance(account);
    console.log("ETH left is: " + balance);
}

// Example code showing how to assign erc20 tokens to test accounts
(async () => {
    const bankjson = require("../../build/contracts/Bank.json");
    const accountsjson = require("../../build/contracts/Accounts.json");
    const savingAccountjson = require("../../build/contracts/SavingAccount.json");
    const erc20json = require("../../build/contracts/MockERC20.json");

    // Please replace all the addresses here to the addresses generated by your deployement
    const account1 = "0xaA817b67d605f45e7759031303b04422734834eD";
    const account2 = "0xBC32e33Ec5e34c7963E3676d35268855eB578475";
    const bankAddress = "0x849Fa13C128D3d322EF95041C4f76A87a3534dCa";
    const accountAddress = "0x3127E5c5C26b7B2Cf45755DF5AF49b41086C9b68";
    const savingAccountAddress = "0xc8b579BAd1cD529C842E45322E4d5Eb135C58b81";
    const daiAddress = "0xF81cc7c9a9F61d6fF36C5cc4ECe8916ce2DdEB14";

    const bankContract = await new web3.eth.Contract(bankjson["abi"], bankAddress);
    const accountContract = await new web3.eth.Contract(accountsjson["abi"], accountAddress);
    const savingAccountContract = await new web3.eth.Contract(savingAccountjson["abi"], savingAccountAddress);
    const daiErc20 = await new web3.eth.Contract(erc20json["abi"], daiAddress);

    // Transfer dai to accounts
    console.log("Tranferring one dai to account 2.");
    await daiErc20.methods.transfer(account2, eighteenDecimals).send({ from: account1, gas: "200000" });
    console.log("Approving saving account to receive dai from account 2.");
    await daiErc20.methods.approve(savingAccountAddress, eighteenDecimals).send({ from: account2, gas: "200000" });
    console.log("Account2 is depositing dai to saving account");
    await savingAccountContract.methods.deposit(daiAddress, eighteenDecimals).send({ from: account2, gas: "2000000" });

    const balance = await accountContract.methods.getDepositPrincipal(account2, daiAddress).call();
    console.log("The balance is: " + balance.toString());
    const daiBalance = await daiErc20.methods.balanceOf(account2).call();
    console.log("The dai balance is: " + daiBalance.toString());
    await getBalance(account2);

    process.exit(0);
})();
