version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.23.0
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      # - image: trufflesuite/ganache-cli
      #   command: ganache-cli --gasLimit 20000000 --gasPrice 20000 --defaultBalanceEther 1000000000 --allowUnlimitedContractSize true

    working_directory: ~/repo

    steps:
      - run:
        |
          sudo apt-get install libudev-dev
          sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.16/solc-static-linux -O /usr/local/bin/solc
          sudo chmod +x /usr/local/bin/solc
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update

      - run: cd compound-protocol && yarn install --lock-file
      - run: cd compound-protocol/scenario && npm i
      - run: sudo npm i
      
      # - run:
      #     name: "Coverage environment"
      #     background: true
      #     command: yarn coverage-setup

      # - run: yarn coverage
      # - run: 
      #     name: Start EVM
      #     background: true
      #     command: npx hardhat node

      - run: 
          name: Run tests
          command: ./runtests.sh  #triggers truffle test